import css from './About.module.css';
import imageX from '../../Image/Images/x.png'
import image from '../../Image/Images/About.png'
import Slider from 'react-slick';

const About = () => {
  const settings = {
    dots: true,
    infinite: true,
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplay: true,
    speed: 2000,
    autoplaySpeed: 2000,
    cssEase: "linear"
  };

  return (
    <div className={css.divAbout}>
      <p className={css.aStoryAbout}>a Story that started with <span className={css.span}>one simple ape</span></p>
      <p className={css.whoGotAbout}>WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT</p>
      <div className={css.divAboutX}>
      <img src={imageX} className={css.x} alt="x"/>
      <p className={css.eachArtworkAbout}>EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE RANDOMLY GENERATED BY USERS</p>
      </div>
      <img src={image} className={css.AboutMonkey} alt="MonkeyAbout"/>
      <div className="slider-container">
      <Slider {...settings}>
        <div>
          <h3>1</h3>
        </div>
        <div>
          <h3>2</h3>
        </div>
        <div>
          <h3>3</h3>
        </div>
      </Slider>
    </div>
    </div>
  );
};

export default About;
